# Generated by Django 4.1.3 on 2022-12-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_alter_train_form_city_alter_train_to_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='form_city',
            new_name='from_city',
        ),
    ]
