# Generated by Django 4.1.3 on 2023-01-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0004_alter_train_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['travel_time'], 'verbose_name': 'Train', 'verbose_name_plural': 'Trains'},
        ),
    ]
