# Generated by Django 4.1.3 on 2023-01-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['travel_times'], 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
    ]
